# Generated by Django 5.2.7 on 2025-10-13 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_financeiro", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usuario",
            old_name="createcleard_at",
            new_name="created_at",
        ),
    ]
