# Generated by Django 5.2.7 on 2025-10-17 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_financeiro", "0002_rename_createcleard_at_usuario_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="idade",
            field=models.DecimalField(decimal_places=0, max_digits=2),
        ),
    ]
